openapi: 3.0.3
info:
  title: Ebaazee Notification Service API
  version: 1.0.0
  description: |
    The Notification Service delivers real-time updates for auctions and bids in Ebaazee.
    It uses WebSocket (Socket.IO) to send live events like new bids, auction start/end notifications, and system alerts.

servers:
  - url: ws://localhost:8083
    description: Local WebSocket server

tags:
  - name: Notifications
    description: Real-time events via WebSocket

paths:
  /notifications:
    get:
      tags:
        - Notifications
      summary: WebSocket connection endpoint
      description: |
        Connect to this endpoint using a WebSocket (Socket.IO) client to receive real-time events.
      responses:
        '101':
          description: WebSocket Upgrade Successful

components:
  schemas:
    NewBidEvent:
      type: object
      properties:
        auctionId:
          type: string
        bidId:
          type: string
        userId:
          type: string
        amount:
          type: number
        timestamp:
          type: string
          format: date-time

    AuctionStatusEvent:
      type: object
      properties:
        auctionId:
          type: string
        status:
          type: string
          enum: [upcoming, live, closed]
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time

    SystemAlert:
      type: object
      properties:
        message:
          type: string
        severity:
          type: string
          enum: [info, warning, critical]
        timestamp:
          type: string
          format: date-time

