openapi: 3.0.3
info:
  title: Ebaazee Payment Service API
  version: 1.0.0
  description: |
    The Payment Service manages payments in Ebaazee.
    It handles initiating transactions, verifying payments, and retrieving payment history.

servers:
  - url: http://localhost:8086
    description: Local development server

tags:
  - name: Payments
    description: Operations related to payments

paths:
  /payments/initiate:
    post:
      tags:
        - Payments
      summary: Initiate a new payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '201':
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Invalid request

  /payments/{paymentId}:
    get:
      tags:
        - Payments
      summary: Get payment status by ID
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Payment status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404':
          description: Payment not found

  /payments/user/{userId}:
    get:
      tags:
        - Payments
      summary: Get payment history for a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of payments made by the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentResponse'

components:
  schemas:
    PaymentRequest:
      type: object
      required:
        - userId
        - auctionId
        - amount
        - paymentMethod
      properties:
        userId:
          type: string
          description: ID of the user making the payment
        auctionId:
          type: string
          description: Auction ID for which the payment is made
        amount:
          type: number
          description: Payment amount
        paymentMethod:
          type: string
          enum: [credit_card, debit_card, net_banking, upi, wallet]
          description: Payment method

    PaymentResponse:
      type: object
      properties:
        paymentId:
          type: string
        userId:
          type: string
        auctionId:
          type: string
        amount:
          type: number
        status:
          type: string
          enum: [pending, successful, failed]
        timestamp:
          type: string
          format: date-time
